#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Testcases for pyhash file

"""
import sys
import unittest
sys.path.append('../')

import pyhash


class TestHashMethods(unittest.TestCase):

    """
    Test cases for functions of text_preprocessing.preprocess module
        - remove_numbers
        - lowercase

    """

    def test_hash_str(self):
        """Summary
        """
        # load data from file:
        # including 2 fields: actual string and hash string (generated by C++)
        data = None
        for actual, h in data:
            self.assertEqual(pyhash.hash(actual), h)

if __name__ == '__main__':
    unittest.main()
